# Generated by Django 2.2.9 on 2020-02-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('COMPROMETIDO', 'Comprometido/a'), ('CASADO', 'Casado/a'), ('UNION', 'Union libre'), ('SEPARADO', 'Separado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('NINGUNO', 'Ninguno')], default='NINGUNO', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO_DESCRIBE', 'Ninguna me describe'), ('NINGUNO', 'Ninguno')], default='NINGUNO', max_length=10),
        ),
    ]
